plugins {
    id 'java-library'
}

dependencies {
    api project(':chat-common')
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'org.springframework.boot:spring-boot-starter-data-redis'
    api 'org.springframework.security:spring-security-core'
    runtimeOnly 'org.postgresql:postgresql'
    runtimeOnly 'com.h2database:h2'
}
