plugins {
    id 'org.springframework.boot'
}

springBoot {
    mainClass = 'com.example.chat.api.ChatApiApplication'
}

dependencies {
    implementation project(':chat-core')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-session-data-redis'
    implementation 'org.webjars:sockjs-client:1.5.1'
    implementation 'org.webjars:stomp-websocket:2.3.4'

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
}
